/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class BinarySearch {
    public static int BinarySearch (int[] arrayToBeChecked, int numberToBeFound) {
        int left = 0;
        int right = arrayToBeChecked.length - 1;
        while (left <= right) {
            int middle = Math.floorDiv(left + right, 2);
            if (arrayToBeChecked[middle] < numberToBeFound) left += 1;
            else if (arrayToBeChecked[middle] > numberToBeFound) right -= 1;
            else return middle;
        }
        return -1;
    }
}
